baseURL = 'https://dimassuryo.com/'
languageCode = 'en-us'
title = 'Dimas Suryo'
disableKinds = ['taxonomy', 'term']

[params]
  tagline = 'Quantitative Analyst | Ultra-Cyclist | Reader & Writer'
  description = "Dimas Suryo's personal site — writing on financial markets, systems thinking, and more."

[menu]
  [[menu.main]]
    name = "About"
    url = "/#about"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 3
  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 4
  [[menu.main]]
    name = "Projects"
    url = "https://tools.dimassuryo.com"
    weight = 5
      [[menu.main]]
    name = "Review"
    url = "/review/"
    weight = 6
    [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true